#!/usr/bin/env bash
set -euo pipefail

PR_NUMBER="${GITHUB_EVENT_NUMBER:-}"
if [[ -z "${PR_NUMBER}" ]]; then
  PR_NUMBER=$(jq -r '.pull_request.number // empty' "${GITHUB_EVENT_PATH}" 2>/dev/null || true)
fi

if [[ -z "${PR_NUMBER}" ]]; then
  echo "::warning::Could not determine PR number, skipping comment"
  exit 0
fi

REPO="${GITHUB_REPOSITORY}"
MARKER="<!-- kube-diff-action -->"
# GitHub rejects comment bodies over 65536 characters; leave room for the title and footer.
MAX_REPORT_LENGTH=60000
# Status labels of kube-diff's color and plain reports (pkg/report/summary.go).
RESOURCE_LINE='^(\* NEW|★ NEW|~ CHANGED|  OK|✓ OK|x DELETED|✗ DELETED) '
ESC=$'\033'

if [[ "${HAS_CHANGES}" == "true" ]]; then
  TITLE="### :warning: Cluster Drift Detected"
else
  TITLE="### :white_check_mark: No Cluster Drift"
fi

REPORT=$(printf '%s\n' "${DIFF_RESULT}" | sed "s/${ESC}\[[0-9;]*m//g")

emit_resource() {
  local resource="$1" diff="$2"
  if [[ -z "${resource}" ]]; then
    return
  fi
  if [[ -n "${diff}" ]]; then
    printf "<details>\n<summary>%s</summary>\n\n\`\`\`diff\n%s\`\`\`\n\n</details>\n\n" "${resource}" "${diff}"
  else
    printf -- '- %s\n' "${resource}"
  fi
}

# Color/plain report: a <details> per changed resource, a bullet for the rest.
render_text() {
  local line resource="" diff=""
  while IFS= read -r line; do
    if [[ "${line}" =~ ${RESOURCE_LINE} ]]; then
      emit_resource "${resource}" "${diff}"
      resource="${line}"
      diff=""
    elif [[ "${line}" == Summary:* ]]; then
      emit_resource "${resource}" "${diff}"
      resource=""
      diff=""
      printf '\n**%s**\n' "${line}"
    elif [[ -n "${resource}" && -n "${line}" ]]; then
      diff+="${line}"$'\n'
    fi
  done <<< "${REPORT}"
  emit_resource "${resource}" "${diff}"
}

# Markdown report: kept as-is, with each "### Kind/name" diff section folded into <details>.
render_markdown() {
  local line open=false
  while IFS= read -r line; do
    if [[ "${line}" == "## kube-diff Report" ]]; then
      continue
    elif [[ "${line}" == "### "* ]]; then
      if [[ "${open}" == "true" ]]; then
        printf '</details>\n\n'
      fi
      printf '<details>\n<summary>%s</summary>\n' "${line#"### "}"
      open=true
    else
      printf '%s\n' "${line}"
    fi
  done <<< "${REPORT}"
  if [[ "${open}" == "true" ]]; then
    printf '\n</details>\n'
  fi
}

# summary-only prints the summary line whatever the output format.
if [[ "${INPUT_SUMMARY_ONLY:-false}" == "true" ]]; then
  FORMATTED_RESULT=$(render_text)
else
  case "${INPUT_OUTPUT:-}" in
    markdown) FORMATTED_RESULT=$(render_markdown) ;;
    json)     FORMATTED_RESULT=$(printf "\`\`\`json\n%s\n\`\`\`" "${REPORT}") ;;
    table)    FORMATTED_RESULT=$(printf "\`\`\`text\n%s\n\`\`\`" "${REPORT}") ;;
    *)        FORMATTED_RESULT=$(render_text) ;;
  esac
fi

if (( ${#FORMATTED_RESULT} > MAX_REPORT_LENGTH )); then
  SUMMARY_LINE=$(grep -m1 -E '^(Summary:|\*\*[0-9]+\*\* resources)' <<< "${REPORT}" || true)
  RUN_URL="${GITHUB_SERVER_URL:-https://github.com}/${REPO}/actions/runs/${GITHUB_RUN_ID:-}"
  FORMATTED_RESULT="${SUMMARY_LINE}

The full report is too large for a PR comment; see the [workflow run](${RUN_URL})."
fi

BODY="${MARKER}
${TITLE}

${FORMATTED_RESULT}

---
*Generated by [kube-diff-action](https://github.com/somaz94/kube-diff-action)*"

# Upsert by marker so reruns edit one comment instead of stacking new ones.
EXISTING_COMMENT_ID=$(gh api "repos/${REPO}/issues/${PR_NUMBER}/comments" \
  --jq ".[] | select(.body | contains(\"${MARKER}\")) | .id" 2>/dev/null | head -1 || true)

if [[ -n "${EXISTING_COMMENT_ID}" ]]; then
  echo "Updating existing comment ${EXISTING_COMMENT_ID}"
  gh api "repos/${REPO}/issues/comments/${EXISTING_COMMENT_ID}" \
    -X PATCH \
    -f body="${BODY}" > /dev/null
else
  echo "Creating new comment on PR #${PR_NUMBER}"
  gh api "repos/${REPO}/issues/${PR_NUMBER}/comments" \
    -f body="${BODY}" > /dev/null
fi

echo "::notice::PR comment posted successfully"
