#!/usr/bin/env bash
set -euo pipefail

PR_NUMBER="${GITHUB_EVENT_NUMBER:-}"
if [[ -z "${PR_NUMBER}" ]]; then
  PR_NUMBER=$(jq -r '.pull_request.number // empty' "${GITHUB_EVENT_PATH}" 2>/dev/null || true)
fi

if [[ -z "${PR_NUMBER}" ]]; then
  echo "::warning::Could not determine PR number, skipping comment"
  exit 0
fi

REPO="${GITHUB_REPOSITORY}"
MARKER="<!-- kube-diff-action -->"

# Build comment body
if [[ "${HAS_CHANGES}" == "true" ]]; then
  TITLE="### :warning: Cluster Drift Detected"
else
  TITLE="### :white_check_mark: No Cluster Drift"
fi

# Parse diff result into per-resource collapsible sections
FORMATTED_RESULT=""
CURRENT_RESOURCE=""
CURRENT_DIFF=""
IN_DIFF=false

while IFS= read -r line; do
  # Detect resource lines (e.g., "★ NEW", "~ CHANGED", "✓ OK", "✗ DELETED", "* NEW", "x DELETED")
  if [[ "${line}" =~ ^[★~✓✗\*x\ ] && ("${line}" =~ NEW || "${line}" =~ CHANGED || "${line}" =~ OK || "${line}" =~ DELETED) ]]; then
    # Flush previous resource
    if [[ -n "${CURRENT_RESOURCE}" ]]; then
      if [[ -n "${CURRENT_DIFF}" ]]; then
        FORMATTED_RESULT+="<details>
<summary>${CURRENT_RESOURCE}</summary>

\`\`\`diff
${CURRENT_DIFF}
\`\`\`

</details>
"
      else
        FORMATTED_RESULT+="- ${CURRENT_RESOURCE}
"
      fi
    fi
    CURRENT_RESOURCE="${line}"
    CURRENT_DIFF=""
    IN_DIFF=false
  elif [[ "${line}" =~ ^(---\ |@@\ ) ]]; then
    IN_DIFF=true
    CURRENT_DIFF+="${line}
"
  elif [[ "${IN_DIFF}" == "true" && -n "${line}" ]]; then
    CURRENT_DIFF+="${line}
"
  elif [[ "${IN_DIFF}" == "true" && -z "${line}" ]]; then
    IN_DIFF=false
  fi
done <<< "${DIFF_RESULT}"

# Flush last resource
if [[ -n "${CURRENT_RESOURCE}" ]]; then
  if [[ -n "${CURRENT_DIFF}" ]]; then
    FORMATTED_RESULT+="<details>
<summary>${CURRENT_RESOURCE}</summary>

\`\`\`diff
${CURRENT_DIFF}
\`\`\`

</details>
"
  else
    FORMATTED_RESULT+="- ${CURRENT_RESOURCE}
"
  fi
fi

# Append summary line (last non-empty line from result)
SUMMARY_LINE=$(echo "${DIFF_RESULT}" | grep -E "^Summary:" || true)
if [[ -n "${SUMMARY_LINE}" ]]; then
  FORMATTED_RESULT+="
**${SUMMARY_LINE}**
"
fi

BODY="${MARKER}
${TITLE}

${FORMATTED_RESULT}
---
*Generated by [kube-diff-action](https://github.com/somaz94/kube-diff-action)*"

# Check for existing comment and update or create
EXISTING_COMMENT_ID=$(gh api "repos/${REPO}/issues/${PR_NUMBER}/comments" \
  --jq ".[] | select(.body | contains(\"${MARKER}\")) | .id" 2>/dev/null | head -1 || true)

if [[ -n "${EXISTING_COMMENT_ID}" ]]; then
  echo "Updating existing comment ${EXISTING_COMMENT_ID}"
  gh api "repos/${REPO}/issues/comments/${EXISTING_COMMENT_ID}" \
    -X PATCH \
    -f body="${BODY}" > /dev/null
else
  echo "Creating new comment on PR #${PR_NUMBER}"
  gh api "repos/${REPO}/issues/${PR_NUMBER}/comments" \
    -f body="${BODY}" > /dev/null
fi

echo "::notice::PR comment posted successfully"
